# Generated by Django 4.2 on 2024-03-15 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(validators=[django.core.validators.EmailValidator()]),
        ),
    ]
