# Generated by Django 4.2 on 2024-03-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_contact', '0002_alter_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
