# Generated by Django 4.2 on 2024-03-25 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_contact', '0004_contact_message_alter_contact_contactchoices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=2200, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
