# Generated by Django 4.2 on 2024-03-25 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crafts_posts', '0006_alter_post_content_alter_post_image_alter_post_owner'),
        ('crafts_likes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeOrUnlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLiked', to='crafts_posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeByUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
