# Generated by Django 4.2 on 2024-03-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_likes', '0002_likeorunlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeOrUnlike',
        ),
    ]
