# Generated by Django 4.2 on 2024-03-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
