# Generated by Django 4.2 on 2024-03-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_panel', '0002_alter_panel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
